#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "gcc -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DL_ENDIAN -DTERMIO -O3 -fomit-frame-pointer -Wall"
  #define PLATFORM "linux-elf"
  #define DATE "Thu Feb 11 18:25:55 EST 2010"
#endif
